In [5]:
import numpy as np

In [6]:
arr1=np.arange(25,35)
arr1

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [7]:
np.save('data', arr1)

In [8]:
arr2=np.load('data.npy')

In [9]:
arr2

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [12]:
arr3=np.random.randint(100,size=(3,10))
arr3

array([[94, 73, 75, 79, 30, 36, 89, 97, 81, 43],
       [51, 34, 77, 91, 77, 29, 55, 47, 65, 54],
       [83, 20, 88,  6, 96, 82, 75,  5, 13, 41]])

In [13]:
arr4=np.random.randint(50,size=(3,10))
arr5=np.arange(20)

In [14]:
np.savez('arrays',a=arr3, b=arr4, c=arr5)

In [15]:
massiv1=np.load('arrays.npz')

In [17]:
massiv1['a']

array([[94, 73, 75, 79, 30, 36, 89, 97, 81, 43],
       [51, 34, 77, 91, 77, 29, 55, 47, 65, 54],
       [83, 20, 88,  6, 96, 82, 75,  5, 13, 41]])

In [24]:
np.sort(massiv1['a'], axis=1)

array([[30, 36, 43, 73, 75, 79, 81, 89, 94, 97],
       [29, 34, 47, 51, 54, 55, 65, 77, 77, 91],
       [ 5,  6, 13, 20, 41, 75, 82, 83, 88, 96]])

In [25]:

np.mean(massiv1['a'])

59.53333333333333

In [26]:
massiv1['b']

array([[25, 15,  9, 11, 30, 26, 15, 41, 26, 13],
       [ 7, 43, 11, 36, 17, 40, 28,  8, 23, 11],
       [43, 47, 44, 31, 15, 11, 14, 35, 36, 21]])

In [27]:
massiv1['c']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [28]:
np.setdiff1d(massiv1['c'],massiv1['b'])

array([ 0,  1,  2,  3,  4,  5,  6, 10, 12, 16, 18, 19])

In [29]:
np.in1d(massiv1['b'],massiv1['c'])

array([False,  True,  True,  True, False, False,  True, False, False,
        True,  True, False,  True, False,  True, False, False,  True,
       False,  True, False, False, False, False,  True,  True,  True,
       False, False, False])

In [30]:
np.savez_compressed('compresarrays',a=arr3,b=arr4,c=arr5)

In [31]:
matn='data.npy'
massiv=np.load(matn)

In [32]:
massiv

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [34]:
a=np.array([[1,2],[3,4]])
print(a.itemsize)

8
