In [2]:
import numpy as np

1 o'lchamli massiv

In [3]:
arr1=np.arange(1,10)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr1[-3]

7

In [5]:
arr1[5]

6

In [6]:
arr2=np.arange(10,100,10)
arr2

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

2 o'lchamli massiv

In [12]:
arr3=np.random.randint(100, size=(4,6))
arr3

array([[66, 49, 97,  4, 16, 14],
       [41, 37, 56, 75, 65, 39],
       [25, 32, 55, 89, 89, 18],
       [95, 51, 16, 69, 23,  1]])

In [13]:
arr3[1,2]

56

In [14]:
arr3[2,3]

89

3 o'lchamli massiv

In [15]:
arr4=np.random.randint(100, size=(3,4,3))
arr4

array([[[ 0, 45, 29],
        [89, 30, 92],
        [97, 45, 40],
        [74, 27, 80]],

       [[95,  6, 81],
        [47,  1, 61],
        [83, 83,  1],
        [66, 25, 15]],

       [[ 1, 37, 57],
        [88, 67, 10],
        [27, 42, 24],
        [62, 67, 91]]])

In [16]:
arr4[1][2,1]

83

In [21]:
sl_arr4=arr4[2][1:3,:].copy()
sl_arr4

array([[88, 67, 10],
       [27, 42, 24]])

Boolean indekslash

In [24]:
ismlar=np.array(['Diyorbek','Sardor','Afzal','Diyorbek','Islom'])
ismlar

array(['Diyorbek', 'Sardor', 'Afzal', 'Diyorbek', 'Islom'], dtype='<U8')

In [25]:
arr5=np.random.randint(100,size=(5,6))
arr5

array([[32,  1, 93, 76, 90, 15],
       [85, 80, 32, 86, 68, 85],
       [44, 59, 13, 65, 76, 15],
       [59, 74, 59, 50, 72, 59],
       [71, 72, 52, 69, 81, 99]])

In [26]:
arr5[ismlar=='Diyorbek']

array([[32,  1, 93, 76, 90, 15],
       [59, 74, 59, 50, 72, 59]])

In [28]:
arr5[ismlar=='Diyorbek', 3:5]

array([[76, 90],
       [50, 72]])

In [29]:
mask=(ismlar=='Diyorbek') | (ismlar=='Afzal')
arr5[mask]

array([[32,  1, 93, 76, 90, 15],
       [44, 59, 13, 65, 76, 15],
       [59, 74, 59, 50, 72, 59]])

In [30]:
mask

array([ True, False,  True,  True, False])

In [31]:
arr5[arr5<30]=0
arr5

array([[32,  0, 93, 76, 90,  0],
       [85, 80, 32, 86, 68, 85],
       [44, 59,  0, 65, 76,  0],
       [59, 74, 59, 50, 72, 59],
       [71, 72, 52, 69, 81, 99]])