# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [23]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.23.5
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [ ]:
royxat=[23,25,6,1,11,10]
royxat_array=np.array(royxat)
royxat_array

array([23, 25,  6,  1, 11, 10])

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

In [ ]:
arr1=np.zeros(9)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [ ]:
massiv=np.random.randint(100, size=(5,6))
massiv

array([[52, 26, 79, 48, 81, 27],
       [78,  5, 89, 94,  3, 71],
       [89, 12, 67,  5, 19, 16],
       [ 5, 52, 26, 92, 26, 44],
       [59, 12, 92, 91,  3, 71]])

In [ ]:
massiv.size

30

In [ ]:
massiv.itemsize

8

#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [ ]:
vektor=np.zeros(12)
vektor[6]=1
vektor

array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [ ]:
arr2=np.arange(20,60)
arr2

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [ ]:
arr3=np.random.randint(25, size=(10))
arr3

array([20,  1, 15,  1,  4, 20, 19, 22,  2, 15])

In [ ]:
arr3=arr3[::-1]
arr3

array([15,  2, 22, 19, 20,  4,  1, 15,  1, 20])

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [ ]:
arr4=np.arange(12,21).reshape(3,3)
arr4

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [3]:
arr5=np.array([3, 7, 0, 0, 9, 0])
np.nonzero(arr5)

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [4]:
arr6=np.random.random(size=(2,2,2))
arr6

array([[[0.46116894, 0.10368238],
        [0.75725986, 0.61379512]],

       [[0.48521194, 0.17355916],
        [0.73806754, 0.11754335]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [5]:
arr7=np.random.randint(100, size=(9,9))
arr7

array([[83,  8, 73, 64, 71, 46, 67, 51, 64],
       [10, 94, 65, 87, 25, 98, 75, 24, 65],
       [22,  1, 48, 68, 68, 19, 39, 53, 80],
       [21, 21, 66, 83, 66, 81, 16, 18, 84],
       [72, 22, 24, 21, 98, 53, 60, 92, 26],
       [52, 57, 88, 29, 50, 77, 35, 65, 85],
       [87, 42,  0,  7, 10, 39, 38, 54,  0],
       [13,  9, 98, 31, 74, 91, 88, 53, 93],
       [ 6, 76, 24, 89, 90, 99, 47, 82, 62]])

In [6]:
np.min(arr7)

0

In [11]:
np.max(arr7)

99

#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [12]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1

False

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [15]:
arr8=np.random.random(size=(6,3))
arr9=np.random.random(size=(3,4))
arr9

array([[0.39483886, 0.5978168 , 0.66367621, 0.0583219 ],
       [0.21623155, 0.31658376, 0.21999391, 0.02345673],
       [0.70389011, 0.95725345, 0.85637645, 0.79763601]])

In [16]:
arr8

array([[0.11471104, 0.20363836, 0.49060518],
       [0.19945653, 0.79142918, 0.183444  ],
       [0.1226092 , 0.02681381, 0.91660679],
       [0.07443845, 0.40143968, 0.34390533],
       [0.06196761, 0.44890419, 0.03650395],
       [0.54515383, 0.4603358 , 0.4683553 ]])

In [17]:
np.dot(arr8,arr9)

array([[0.43465755, 0.60267828, 0.54107291, 0.40279121],
       [0.37900956, 0.54539449, 0.46358127, 0.17651857],
       [0.69939933, 0.95921166, 0.87223215, 0.73889834],
       [0.35826668, 0.5007944 , 0.43222973, 0.28806913],
       [0.14722924, 0.21410459, 0.17114374, 0.04326076],
       [0.6444577 , 0.91997168, 0.86416514, 0.41616943]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

10

#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [27]:
a=np.array([1,2])
b=np.array([4,5])
a>b


array([False, False])

In [28]:
a>=b

array([False, False])

In [29]:
a<b

array([ True,  True])

In [30]:
a<=b

array([ True,  True])

#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [31]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-31-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-31-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [32]:
arr15=np.random.randint(10,25,8)
arr16=np.random.randint(10,25,8)
print(arr15)
print(arr16)

[10 10 23 18 18 23 11 22]
[18 15 24 19 10 15 18 24]


In [33]:
np.intersect1d(arr15,arr16)

array([10, 18])

#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [41]:
arr19=np.array([1.2, 2.5, 3.7, 4.1, 5.9])
arr19

array([1.2, 2.5, 3.7, 4.1, 5.9])

In [42]:
np.floor(arr19)

array([1., 2., 3., 4., 5.])

In [43]:
np.trunc(arr19)

array([1., 2., 3., 4., 5.])

In [44]:
arr18=arr19.astype(int)
arr18

array([1, 2, 3, 4, 5])

#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [58]:
matrix = np.tile(np.arange(3), (3, 1))     #Bu funksiya bir massivni istalgan qator (row) va ustunga (column) ko'paytirib nusxalaydi.
print(matrix)

[[0 1 2]
 [0 1 2]
 [0 1 2]]


#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [59]:
array=np.random.randint(100, size=(10))
array

array([45, 92, 22, 23, 15, 46, 42,  0, 80, 52])

In [62]:
np.sort(array)

array([ 0, 15, 22, 23, 42, 45, 46, 52, 80, 92])

#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [70]:
A = np.random.rand(3, 4)
B = np.random.rand(3, 4)
print(A)
print('\n',B)

[[0.51642069 0.71448992 0.28856532 0.99916085]
 [0.12652698 0.3991222  0.62972424 0.74761232]
 [0.91476503 0.06106625 0.94672933 0.15008115]]

 [[0.12591208 0.70030928 0.97982556 0.70419717]
 [0.46217908 0.65824291 0.2606022  0.88802676]
 [0.74656129 0.94573303 0.10311145 0.67922187]]


In [71]:
arr_equal=np.array_equal(A,B)
arr_equal

False

#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [66]:
array1=np.random.randint(10, size=(6,3))
array2=np.random.randint(10, size=(3,4))
np.dot(array1,array2)

array([[ 30, 110,  63,  50],
       [ 45, 158, 119,  77],
       [  5,  98,  70,  27],
       [  0,   7,   0,   1],
       [  0, 105,  49,  21],
       [ 25,  32,  35,  31]])

#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [75]:
vektor1=np.random.randn(5)
vektor1

array([ 0.09159475, -0.18409963,  0.62854723, -0.17787457, -1.45733574])

In [76]:
vektor1[argmax(vektor1)]=0  #argmax massivning eng katta elementini indexini qaytaradi
vektor1

array([ 0.09159475, -0.18409963,  0.        , -0.17787457, -1.45733574])

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [83]:
import numpy as np
today = np.datetime64('today', 'D')
tomorrow = today + np.timedelta64(1, 'D')
yesterday = today - np.timedelta64(1, 'D')

print("Bugun:", today)
print("Ertaga:", tomorrow)
print("Kecha:", yesterday)

Bugun: 2023-11-09
Ertaga: 2023-11-10
Kecha: 2023-11-08


#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [85]:
boshi = np.datetime64('2016-01-01')
oxiri = np.datetime64('2016-02-01')
barcha_kunlar = np.arange(boshi, oxiri, dtype='datetime64[D]')

print(barcha_kunlar)


['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30'
 '2016-01-31']


#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [93]:
arr27=np.random.randn(6)  # bu misol qayta takrorlangan
np.trunc(arr27)

array([ 0.,  0.,  1., -1., -1.,  0.])

#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [94]:
arr = np.array([1, 2, 3, 4, 5])
natija = np.add.reduce(arr)

print(natija)


15


#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [98]:
original_array = np.array([1, 2, 3, 4, 5])
new_array = np.repeat(original_array, 4)
new_array[1::4] = 0
new_array[2::4] = 0
new_array[3::4] = 0

print(new_array)


[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5 0 0 0]


#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [104]:
from numpy.lib.stride_tricks import as_strided        #o'xshamadi
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
b = as_strided(a, shape=(11, 4), strides=(4, 4))
print(b)


[[          1  8589934592           2 12884901888]
 [ 8589934592           2 12884901888           3]
 [          2 12884901888           3 17179869184]
 [12884901888           3 17179869184           4]
 [          3 17179869184           4 21474836480]
 [17179869184           4 21474836480           5]
 [          4 21474836480           5 25769803776]
 [21474836480           5 25769803776           6]
 [          5 25769803776           6 30064771072]
 [25769803776           6 30064771072           7]
 [          6 30064771072           7 34359738368]]


#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [106]:
massiv2=np.random.randint(20, size=(10))       #o'xshamadi
massiv2

array([17,  6,  4,  8, 11, 13,  8,  9,  8, 18])

#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`