In [1]:
import numpy as np

In [2]:
list1=[20,3,4.5,7,-5]
arr1=np.array(list1)

In [3]:
list1

[20, 3, 4.5, 7, -5]

In [4]:
arr1

array([20. ,  3. ,  4.5,  7. , -5. ])

.ndim metodi

In [40]:
arr1.ndim  #massiv o'lchamini ko'rsatadi

1

2 o'lchamli massiv yaratish

In [24]:
list3=[[2,34,6.5,3],[33,6.7,8.7,5]]
arr3=np.array(list3)

In [25]:
arr3

array([[ 2. , 34. ,  6.5,  3. ],
       [33. ,  6.7,  8.7,  5. ]])

In [26]:
arr3.ndim

2

.shape va .size metodlari

In [27]:
arr3.shape  #qator va ustunlarni tuple ko'rinishida qaytaradi

(2, 4)

In [28]:
arr3.size   #massiv elementlari sonini ko'rsatadi

8

massiv yaratishning boshqa usullari

In [44]:
arr4=np.zeros((3,3))  #faqat nollardan iborat massiv , qavs ichiga massiv ustun va qatorlari yoziladi ya'ni shape

In [42]:
arr5=np.ones(shape=(4,4))  #faqat 1 lardan iborat massiv, qavs ichida massiv shape'i

In [31]:
print(arr4)
print(arr5)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


arange funksiyasi

In [47]:
arr6=np.arange(1,100,2)   #1 dan 100gacha (100 kirmaydi) 2 ta qadam bilan massiv yaratadi
arr6

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [48]:
arr7=np.arange(25)
arr7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

random funksiyasi

In [52]:
arr8=np.random.randint(100, size=(2,6))  #min va max qiymat, size beriladi, tasodifiy butun sonlardan iborat massiv yaratadi
arr8

array([[81, 10, 44, 18, 62, 83],
       [56, 70, 90, 20,  5, 71]])

In [56]:
arr9=np.random.rand(2,5)   # 0 va 1 oraliqdagi random sonlar
arr9

array([[0.97588062, 0.27254537, 0.11005646, 0.07542833, 0.87826955],
       [0.64308263, 0.43344597, 0.12959663, 0.3718093 , 0.60446638]])

In [57]:
arr10=np.random.randn(2,4)
arr10

array([[-1.77442444e-01, -8.02866731e-02,  1.11891402e+00,
        -9.24111897e-01],
       [-2.85767178e-01, -2.23272095e-01, -2.21783072e-03,
        -2.52171750e+00]])