In [1]:
import numpy as np

.dtype metodi

In [3]:
arr1=np.array([12,23,3.4,5])
arr1.dtype

dtype('float64')

In [8]:
arr2=np.array([10,2,11,3], dtype=np.int16)
arr2.dtype

dtype('int16')

In [7]:
arr3=np.array([56,545,2,1,14], dtype=np.float64)
arr3

array([ 56., 545.,   2.,   1.,  14.])

.astype metodi

In [9]:
int_arr1=arr1.astype(np.int64)
int_arr1

array([12, 23,  3,  5])

In [10]:
float_arr2=arr2.astype(np.float32)
float_arr2

array([10.,  2., 11.,  3.], dtype=float32)