In [1]:
import numpy as np

In [2]:
arr1=np.random.randint(10,100, size=(6))
arr1

array([80, 30, 32, 28, 52, 84])

unary funksiyalar - bitta argument qabul qiluvchi funksiyalar

In [3]:
np.sqrt(arr1)

array([8.94427191, 5.47722558, 5.65685425, 5.29150262, 7.21110255,
       9.16515139])

In [4]:
np.square(arr1)

array([6400,  900, 1024,  784, 2704, 7056])

In [5]:
np.log(arr1)

array([4.38202663, 3.40119738, 3.4657359 , 3.33220451, 3.95124372,
       4.4308168 ])

binary- 2 ta argument qabul qiluvchi funksiya

In [17]:
arr2=np.random.randint(10,100, size=(6))
arr2

array([72, 52, 21, 18, 55, 89])

In [18]:
np.sign(arr2)

array([1, 1, 1, 1, 1, 1])

In [19]:
np.maximum(arr1,arr2)

array([80, 52, 32, 28, 55, 89])

In [20]:
np.add(arr1,arr2)

array([152,  82,  53,  46, 107, 173])

In [22]:
np.mod(arr1,arr2)

array([ 8, 30, 11, 10, 52, 84])