In [2]:
import numpy as np

In [ ]:
array=np.random.randint(25,50, size=(5,7))
array

array([[33, 25, 29, 27, 43, 38, 28],
       [49, 26, 45, 36, 25, 32, 28],
       [38, 28, 27, 40, 40, 27, 29],
       [39, 33, 44, 42, 33, 37, 31],
       [33, 30, 48, 42, 47, 42, 31]])

In [ ]:
natija=np.where(array<=40, 0,1)
natija

array([[0, 0, 0, 0, 1, 0, 0],
       [1, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 0],
       [0, 0, 1, 1, 1, 1, 0]])

arifmetik amallar

In [ ]:
arr1=np.arange(1,10).reshape(3,3)
arr2=np.random.randint(10,100, size=(3,3))

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2

array([[83, 32, 24],
       [12, 75, 56],
       [37, 44, 61]])

In [ ]:
arr1+arr2

array([[84, 34, 27],
       [16, 80, 62],
       [44, 52, 70]])

In [ ]:
arr2/arr1

array([[83.        , 16.        ,  8.        ],
       [ 3.        , 15.        ,  9.33333333],
       [ 5.28571429,  5.5       ,  6.77777778]])

In [ ]:
arr2**0.5

array([[9.11043358, 5.65685425, 4.89897949],
       [3.46410162, 8.66025404, 7.48331477],
       [6.08276253, 6.63324958, 7.81024968]])

In [ ]:
arr1**3

array([[  1,   8,  27],
       [ 64, 125, 216],
       [343, 512, 729]])

In [ ]:
arr1*arr2

array([[ 83,  64,  72],
       [ 48, 375, 336],
       [259, 352, 549]])

matematik va statistik amallar

In [ ]:
arr2.mean()

47.111111111111114

In [ ]:
np.mean(arr2)  #o'rtacha qiymat

47.111111111111114

In [ ]:
arr2.mean(axis=0)  #o'qlar bo'yicha o'rtacha qiymat

array([44.        , 50.33333333, 47.        ])

In [ ]:
arr2.mean(axis=1)

array([46.33333333, 47.66666667, 47.33333333])

In [ ]:
arr1.sum()  #yig'indi

45

In [ ]:
np.sum(arr2)

424

In [ ]:
arr1.cumsum()  #yig'indini yig'ib boradigan metod

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [ ]:
arr1.prod()    #ko'paytmani yig'indisi

362880

In [ ]:
arr4=np.random.randint(100, size=(4,8))
arr4

array([[88, 15, 61, 38,  9, 20,  0, 52],
       [69, 89, 88, 99, 28, 61, 37, 10],
       [73,  8, 50, 14, 88, 32, 19, 62],
       [85, 14, 32, 82, 25, 63, 21, 19]])

sorting(tartiblash)

In [ ]:
arr4.sort()
arr4

array([[ 0,  9, 15, 20, 38, 52, 61, 88],
       [10, 28, 37, 61, 69, 88, 89, 99],
       [ 8, 14, 19, 32, 50, 62, 73, 88],
       [14, 19, 21, 25, 32, 63, 82, 85]])

In [ ]:
arr4.sort(axis=0)
arr4

array([[ 0,  9, 15, 20, 32, 52, 61, 85],
       [ 8, 14, 19, 25, 38, 62, 73, 88],
       [10, 19, 21, 32, 50, 63, 82, 88],
       [14, 28, 37, 61, 69, 88, 89, 99]])

In [ ]:
-np.sort(-arr4, axis=1)

array([[85, 61, 52, 32, 20, 15,  9,  0],
       [88, 73, 62, 38, 25, 19, 14,  8],
       [88, 82, 63, 50, 32, 21, 19, 10],
       [99, 89, 88, 69, 61, 37, 28, 14]])

unique va in1d, setdiff1d

In [3]:
sonlar=np.array([12,23,34,3,1,2,1,22,5.6,6,6,34])
np.unique(sonlar)

array([ 1. ,  2. ,  3. ,  5.6,  6. , 12. , 22. , 23. , 34. ])

In [5]:
raqamlar=np.array([12,23,6])
np.in1d(sonlar,raqamlar)

array([ True,  True, False, False, False, False, False, False, False,
        True,  True, False])

In [6]:
ism1=np.array(['Diyorbek','Jamshid','Bekzod','Anvar','Doniyor','Akbar'])
ism2=np.array(['Akobir','Humoyun','Hadicha','Anvar','Jamshid','Bekzod'])

In [7]:
np.setdiff1d(ism1,ism2)

array(['Akbar', 'Diyorbek', 'Doniyor'], dtype='<U8')